#!/bin/bash

[ -n "$URL" ] || { echo Error: Missing URL environment variable; exit 1; }

[ -e build ] && { echo Error: The build directory already exists; exit 1; }

mkdir -p build
cd build

wget -k -K -E -r -l 10 -p -N -F --restrict-file-names=windows -nH "$URL"

